

:linkcss:
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: stylesheets/
:stylesheet: colony.css
:data-uri:
:toc:

== References

https://satsang.arshavidya.org/swami-tattvavidananda/

https://templesinindiainfo.com/shrimad-bhagavadgitashankarabhashyam-lyrics-in-telugu/

== Sankara Bhashyam (Introduction)

1)  link:./images/audios/0-introduction/intro-1.mp3[ సః భగవాన్]

    సః భగవాన్
    వాసుదేవః
    సృష్ట్వా-ఇదం జగత్,
    తస్య చ స్థితిం చికీర్షుః,
    మరీచి-ఆదీన్-అగ్రే సృష్ట్వా
    ప్రజాపతీన్,
    ప్రవృత్తి-లక్షణం ధర్మం
    గ్రాహయామాస వేద-ఉక్తం ।

    తతః అన్యాణ్ చ
    సనక-సనందన-ఆదీన్
    ఉత్పాద్య,
    నివృత్తి-లక్షణం ధర్మం
    జ్ఞాన-వైరాగ్య-లక్షణం
    గ్రాహయామాస ।

    ద్వివిధః హి
    వేదోక్తః ధర్మః,
    ప్రవృత్తి-లక్షణః నివృత్తి-లక్షణః చ ।
    జగతః స్థితి-కారణం ,
    ప్రాణినాం
    సాక్షాత్-అభ్యుదయ-నిఃశ్రేయస-హేతుః
    యః సః ధర్మః
    బ్రాహ్మణాద్యైః
    వర్ణిభిః
    ఆశ్రమిభిః చ శ్రేయోర్థిభిః
    అనుష్ఠీయమానః ।

2  link:./images/audios/0-introduction/intro-1.mp3[ దీర్ఘేణ]

    దీర్ఘేణ కాలేన
    అనుష్ఠాతృఈణాం
    కామ-ఉద్భవాత్
    హీయమాన-వివేక-విజ్ఞాన-హేతుకేన
    అధర్మేణ
    అభిభూయమానే ధర్మే,
    ప్రవర్ధమానే చ అధర్మే,
    జగతః స్థితిం
    పరిపిపాలయిషుః
    సః ఆదికర్తా
    నారాయణ-ఆఖ్యః
    విష్ణుః
    భౌమస్య బ్రహ్మణః
    బ్రాహ్మణత్వస్య
    రక్షణార్థం
    దేవక్యాం
    వసుదేవాత్-
    అంశేన కృష్ణః కిల సంబభూవ ।

    బ్రాహ్మణత్వస్య హి రక్షణే
    రక్షితః స్యాత్
    వైదికః ధర్మః,
    తత్-అధీనత్వాత్
    వర్ణ-ఆశ్రమ-భేదానాం ॥

3   link:./images/audios/0-introduction/intro-3.mp3[ సః చ భగవాన]

    సః చ భగవాన్
    జ్ఞాన-ఐశ్వర్య-శక్తి-బల-వీర్య-తేజోభిః సదా సంపన్నః
    త్రిగుణ-ఆత్మికాం స్వాం మాయాం మూల-ప్రకృతిం వశీకృత్య,
    అజః
    అవ్యయః
    భూతానాం-ఈశ్వరః
    నిత్య-శుద్ధ-బుద్ధ-ముక్త-స్వభావః అపి సన్,
    స్వ-మాయయా దేహవాన్ ఇవ జాతః
    ఇవ చ
    లోక-అనుగ్రహం కుర్వన్ లక్ష్యతే ।


4  link:./images/audios/0-introduction/intro-4.mp3[ స్వప్రయోజన]

    స్వప్రయోజన-అభావేఽపి
    భూత-అనుజిఘృక్షయా
    వైదికం ధర్మ-ద్వయం
    అర్జునాయ
    శోక-మోహ-మహా-ఉదధౌ
    నిమగ్నాయ
    ఉపదిదేశ,

5 link:./images/audios/0-introduction/intro-5.mp3[ గుణ-అధికైః]

గుణ-అధికైః హి గృహీతః
అనుష్ఠీయమానః చ
ధర్మః
ప్రచయం
గమిష్యతీతి ।

6 link:./images/audios/0-introduction/intro-6.mp3[ తం ధర్మం]

    తం ధర్మం
    భగవతా
    యథా-ఉపదిష్టం
    వేదవ్యాసః
    సర్వజ్ఞః భగవాన్
    గీతా-ఆఖ్యైః సప్తభిః
    శ్లోక-శతైః ఉపనిబబంధ ॥

7 link:./images/audios/0-introduction/intro-7.mp3[ తత్]

    తత్
    ఇదం గీతా-శాస్త్రం సమస్త-వేదార్థ-సార-సంగ్రహ-భూతం
    దుర్విజ్ఞేయ-అర్థం,
    తత్-అర్థ-ఆవిష్కరణాయ
    అనేకైః వివృత-పద-పదార్థ-వాక్యార్థ-న్యాయం-అపి
    అత్యంత-విరుద్ధ-అనేక-అర్థవత్వేన
    లౌకికైః గృహ్యమాణం-ఉపలభ్య
    అహం వివేకతః అర్థ-నిర్ధారణార్థం సంక్షేపతః వివరణం కరిష్యామి ॥


== Approach to Gita

1. Understand each word - including its grammatical aspects.
2. Synthesize the spirit of each verse - not in isolation but in-sync  with ఉపనిషద్ wisdom.
3. కంఠస్థ - Entire verse or a statement or 2 from each verse should be in your కంఠ -
not memoryస్థ or bookస్థ or shelfస్థ. Not the translated meaning but the actual Sanskrit word / statement.

జగత ఈశధీ యుక్త సేవనం

తడ బడు అడుగుల బుడతడి కైనా +
వడి వడి పరుగుల గడ సరి కైనా +
అడు గిడు సందడి కది ఆధారం +
అడుగును కిందకి ఈడ్వడమై (gravity) +
పుడమిని ఇమిడిన ఈశ్వరుడే +

గుడి లో గడపకి అవతల ఉన్నది +
వాడే దేముడు అనుకుంటూ +

మడి తో చేసే  పూజ కి మెచ్చి +
అడిగిన వన్నీ ఇచ్చే వాడని +

నమ్మే మూర్ఖుడి  గడ బిడ తీర్చుట +
ఈశుడి కైనా  గడవని పనిలే ! +

నేనూ నాదను +
అహమే ఇహలో +
మోహాజాలం +
మీలో నాలో +
మారడమంటే +
యేదో కాదు +
గారడి నుంచీ +
వేరగుటేను +
మరిన నాడే +
తీరును దుఃఖం +
మరిన వాడే +
చేరును గమ్యం +



== Meaning of Geeta

    తత్
    ఇదం
    గీతా-శాస్త్రం
    సమస్త-వేదార్థ-సార-సంగ్రహ-భూతం
    దుర్విజ్ఞేయ-అర్థం,


    తత్-అర్థ-ఆవిష్కరణాయ
    అనేకైః వివృత-పద-పదార్థ-వాక్యార్థ-న్యాయం-అపి
    అత్యంత-విరుద్ధ-అనేక-అర్థవత్వేన లౌకికైః గృహ్యమాణం-ఉపలభ్య
    అహం వివేకతః అర్థ-నిర్ధారణార్థం సంక్షేపతః వివరణం కరిష్యామి ॥

link:./images/audios/0-introduction/Geeta_meaning.mp3[Geeta meaning] +

link:./images/audios/0-introduction/Geetha_meaning_2.mp3[Geeta meaning Continued] +

link:./images/audios/0-introduction/Geeta_Song.mp3[Geeta Song Meaning] +

== Vishnu Purana Sloka

=== Telugu Version

1.

     నారాయణః పరోఽవ్యక్తాత్ అండమవ్యక్తసంభవం ।
     అండస్యాంతస్త్విమే లోకాః సప్తద్వీపా చ మేదినీ ॥


link:./images/audios/0-introduction/narayana_meaning.mp3[Narayana Meaning]

link:./images/audios/0-introduction/narayana_meaning_2.mp3[Narayana Meaning Continued]

2

     నారాయణం నమస్కృత్య నరం చైవ నరోత్తమమ్
     దేవీం సరస్వతీం వ్యాసం తతో జయముదీరయేత్

link:./images/audios/0-introduction/Vishunu_purana_2.mp3[Vishunu SLoka 2] +

link:./images/audios/0-introduction/Vishunu_purana_2_2.mp3[Vishunu SLoka 2 Continued] +

=== English Version

link:./images/audios/0-introduction/Vishunu_purana_sloka_2_English.mp3[Vishunu SLoka 2 _ English ] +

link:./images/audios/0-introduction/Vishunu_purana_sloka_2_2_English.mp3[Vishunu SLoka 2 - English - Continued] +


