

:linkcss:
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: stylesheets/
:stylesheet: colony.css
:data-uri:
:toc:

== References

https://satsang.arshavidya.org/swami-tattvavidananda/

https://templesinindiainfo.com/shrimad-bhagavadgitashankarabhashyam-lyrics-in-telugu/


== Approach to Gita

1. Understand each word - including its grammatical aspects.
2. Synthesize the spirit of each verse - not in isolation but in-sync  with ఉపనిషద్ wisdom.
3. కంఠస్థ - Entire verse or a statement or 2 from each verse should be in your కంఠ -
not memoryస్థ or bookస్థ or shelfస్థ. Not the translated meaning but the actual Sanskrit word / statement.

జగత ఈశధీ యుక్త సేవనం

తడ బడు అడుగుల బుడతడి కైనా +
వడి వడి పరుగుల గడ సరి కైనా +
అడు గిడు సందడి కది ఆధారం +
అడుగును కిందకి ఈడ్వడమై (gravity) +
పుడమిని ఇమిడిన ఈశ్వరుడే +

గుడి లో గడపకి అవతల ఉన్నది +
వాడే దేముడు అనుకుంటూ +

మడి తో చేసే  పూజ కి మెచ్చి +
అడిగిన వన్నీ ఇచ్చే వాడని +

నమ్మే మూర్ఖుడి  గడ బిడ తీర్చుట +
ఈశుడి కైనా  గడవని పనిలే ! +

నేనూ నాదను +
అహమే ఇహలో +
మోహాజాలం +
మీలో నాలో +
మారడమంటే +
యేదో కాదు +
గారడి నుంచీ +
వేరగుటేను +
మరిన నాడే +
తీరును దుఃఖం +
మరిన వాడే +
చేరును గమ్యం +




== Sanskrit

అకారాంత (short అ ending) words are usually Masculine in gender classification and
ఆకారంత (దీర్ఘ అ ending) words are of feminine gender.

గీతా is called  సంస్కార గ్రంధః
సంస్కార consists of దోషాపనయనం and గుణాధానం
దోషాపనయనం దోష + అపనయనం (means elimination)
గుణాధానం - గుణ + ఆధాన (means embellishment or placing).

Nouns have gender (M F N)

Nouns in Sanskrit, as in English, are spoken of as substantives (e.g., in possessing సత్త్వ, “substance”).
English only shows gender in the 3rd person pronoun (e.g., “he,” “she,” “it”).
Every noun in Sanskrit has an inherent gender (as in German, French, etc.).

Gender—masculine, feminine, and neuter—is therefore a conventional (philological gender) rather than biological fact in Sanskrit.

While males (male animals, titles, etc.) tend to be masculine and females tend to be feminine.
However there are many exceptions.
For example, one word for wife (దార) is masculine.
One word for friend is neuter (మిత్ర) while another is masculine (సహాయ).
​
The reason you need to know a word’s gender is because words of different genders often take different case-endings.

For example,
The masculine singular nominative case-ending for -a final stems is ః (కూప → nom. కూపః),
The same for neuters is మ్ (వన → nom. వనమ్).

== Meaning of Geeta

తత్
ఇదం
గీతా-శాస్త్రం
సమస్త-వేదార్థ-సార-సంగ్రహ-భూతం
దుర్విజ్ఞేయ-అర్థం,

Todays Audio 2
తత్-అర్థ-ఆవిష్కరణాయ
అనేకైః వివృత-పద-పదార్థ-వాక్యార్థ-న్యాయం-అపి
అత్యంత-విరుద్ధ-అనేక-అర్థవత్వేన లౌకికైః గృహ్యమాణం-ఉపలభ్య
అహం వివేకతః అర్థ-నిర్ధారణార్థం సంక్షేపతః వివరణం కరిష్యామి ॥

link:./images/audios/0-introduction/Geeta_meaning.mp3[Geeta meaning] +

link:./images/audios/0-introduction/Geetha_meaning_2.mp3[Geeta meaning Continued] +

link:./images/audios/0-introduction/Geeta_Song.mp3[Geeta Song Meaning] +

== Vishnu Purana Sloka

=== Telugu Version

1.

నారాయణః పరోఽవ్యక్తాత్ అండమవ్యక్తసంభవం ।
అండస్యాంతస్త్విమే లోకాః సప్తద్వీపా చ మేదినీ ॥ +


link:./images/audios/0-introduction/narayana_meaning.mp3[Narayana Meaning]

link:./images/audios/0-introduction/narayana_meaning_2.mp3[Narayana Meaning Continued]

2.

నారాయణం నమస్కృత్య నరం చైవ నరోత్తమమ్
దేవీం సరస్వతీం వ్యాసం తతో జయముదీరయేత్

link:./images/audios/0-introduction/Vishunu_purana_2.mp3[Vishunu SLoka 2] +

link:./images/audios/0-introduction/Vishunu_purana_2_2.mp3[Vishunu SLoka 2 - Continued] +

=== English Version

link:./images/audios/0-introduction/Vishunu_purana_sloka_2_English.mp3[Vishunu SLoka 2 _ English ] +

link:./images/audios/0-introduction/Vishunu_purana_sloka_2_2_English.mp3[Vishunu SLoka 2 - English - Continued] +



@Courtesy: Dr.Lakshmana Rao Ayyagari. @copy-right to Raghavi Janaswamy and Dr.Lakshamana Rao Ayyagari
