

:linkcss:
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: stylesheets/
:stylesheet: colony.css
:data-uri:
:toc:


== Definitions from Upanishads/Geeta (TVS Pravachanams)

link:./images/audios/0-upanishad/upanishad_1.mp3[Upanishad 1 ] +

link:./images/audios/0-upanishad/upanishad_2.mp3[Upanishad 2 ] +

link:./images/audios/appendix/brahman-eswara-reality.mp3[Brahma/Eswara/Reality ] +

link:./images/audios/appendix/gudakesa.mp3[Gudakesa ] +

link:./images/audios/appendix/hruseekesha.mp3[Hrusheekesha ] +

link:./images/audios/appendix/parantapa.mp3[Parantapa ] +

link:./images/audios/appendix/appendix-5.mp3[Summary of definitions ] +

== ఉపనిషద్

This is the most comprehensive and authentic explanation for the word “ఉపనిషద్”,
with the most minute details.

Refer to first line of Verse 26 in chapter 3 BG.

https://www.gitasupersite.iitk.ac.in/srimad?&language=te&field_chapter_value=3&field_nsutra_value=26

link:./images/audios/appendix/upanishads_meaning.mp3[Upanishad ]

link:./images/audios/appendix/upanishad_meaning_tadhacha.mp3[Tadhacha ]

== becoming vs being

link:./images/audios/appendix/becoming-vs-being.mp3[Becoming vs Being] +

link:./images/audios/appendix/becoming-vs-being-2.mp3[Becoming vs Being Continued ] +


== Upanishads

ఋషి's are OUR Ancestry.   +
They had a vision. +
A vision formulated by deep contemplative thinking. +
Like Newton contemplated and saw "Gravity" in his vision, +
Like Einstein contemplated and saw Time / Space fabric which can be warped,

OUR ఋషి's contemplated and saw this universe and creation in a unique way.
And they expressed their views in ఉపనిషద్'s.
We should be able to understand this and explain it to others.
After getting a grasp of it you will be able to say and FEEL
That “The world is perfect and Life is beautiful”.

This has to be the pinnacle of human intelligence.

    ధన వాన్ - the one who has ధన
    గుణ వాన్ - the one who has గుణ

    similarly
    భగ వాన్ the one who has "భగ"
    "భగ" is a combination of 6 attributes

In this audio you will find
definition of భగవాన్, మూల ప్రకృతి, 3 గుణ's, మాయ
మాయ is 2 words - "మా" "య"  2 single syllable words.

    సః చ భగవాన్ జ్ఞాన-ఐశ్వర్య-శక్తి-బల-వీర్య-తేజోభిః సదా సంపన్నః
    త్రిగుణ-ఆత్మికాం స్వాం మాయాం మూల-ప్రకృతిం వశీకృత్య,
    అజః
    అవ్యయః
    భూతానాం-ఈశ్వరః
    నిత్య-శుద్ధ-బుద్ధ-ముక్త-స్వభావః అపి సన్,
    స్వ-మాయయా దేహవాన్ ఇవ జాతః
    ఇవ చ
    లోక-అనుగ్రహం కుర్వన్ లక్ష్యతే ।



