

:linkcss:
:imagesdir: ./images
:iconsdir: ./icons
:stylesdir: stylesheets/
:stylesheet:  colony.css
:data-uri:
:toc:


Mind matters in matters of body health.

At Mind level - Replace తృష్ణ by కృష్ణ.
At body level - Replace Carbs by Ketones.
One need కృష్ణ and Ketones. PERIOD. (If your objective and focus is Health and enjoyment)

What కృష్ణ (means BG) does at the mind level Ketones do the same thing at body level by getting rid of all toxic molecules from body (including cancer causing). Chronic inflammation is the root cause for many of the diseases of aging - Diabetes, obesity, Hypertension, heart attacks, strokes etc.,
Beta hydroxy Butyrate (BHB) is a very powerful molecule. It is a Ketone (along with Acetoacetate).


=== Other stuff

Foundation - Foundation - Foundation.

Every verse you come to see either in భగవద్గీతా or any other ప్రకరణ గ్రంధాః (eg: భజ గోవిందం, ఆత్మ బోధ, ఉపదేశ సారం, ఉపదేశ పంచకం etc.,) that you come across has to be in line with the vision of the ఉపనిషద్.

That is the way you have to interpret every verse.

But unfortunately both the students and teachers forget this fundamental fact and interpret the spiritual verses according to their whims and fancies, and always if not mostly their own egoistic ideas coloring the interpretation and calling it personality development or భక్తి  or whatever etc.,

This is very unfortunate, because in the end it doesn’t do any good to the student or teacher and they remain stuck in their మోహకలిలం.

What would a ఋషి (also called తత్వ దర్శి) see in his deep contemplative mind, when it is focused on finding answers about this universe and its creation. That formed the central theme of ఉపనిషద్.

Newton saw gravity.
Einstein saw Time/space Fabric that is stretchable.
Einstein was not the author of E=MC2.
Newton was not the author of laws of motion.
Laws of motion and E=MC2 are part of the creation.
They were there at the moment of big bang.
They were merely seen by a contemplative mind.
They were revealed to Newton and Einstein and many others like them.
There were hundreds or even thousands of individuals thinking in the same fashion as newton or Einstein and that is why those proposals were quickly accepted as the final truth for that moment.

What ఋషి’s (also called తత్వ దర్శి’s) saw is that, At the end of dissection Diversity disappears.

They saw Oneness of everything.

“Oneness of everything” is the central and only theme of ఉపనిషద్.
And for this to be absorbed by an ordinary human mind
They said this పదే పదే (again and again) and in different utterances and from  various angles. Hence so many ఉపనిషద్s.

We experience every day the sunrise and sunset. But for a modern man it is easy to understand that the Sun neither rises nor sets down.

The flat earth society is still in existence and we can not help them, because they are “STUCK” (meaning of word మూఢాః).

The truth seen by ఉపనిషద్ ఋషి’s is not that easy to grasp. It is beyond human comprehension, unless one contemplates on it to the same extent that they did.

I just simply can’t comprehend the fact that time is stretchable. I have to accept it and use it to gain from it (like using my navigation system).

The same way I just can not comprehend the fact that in reality there is no world out there. There is only “ONENESS”. Division is a delusion.

But with continuous శ్రవణం, మననం and నిధిధ్యాస, we will gradually, but surely begin to realize the ephemerality of every feeling that is generated by our అహంకార (Done by me - accomplished by me).

I love స్వామీ తత్త్వవిదానంద సరస్వతి’s commentary on the First verse of భగవద్గీతా and today I am sharing this with you all.

And in fact this is the discussion I had with all the three millennials in my house today (Son Praveen, his wife Monisha and my daughter Susmita). They liked it. And I am hoping that you also will like it and share it with others.

Millennials need this very much, because the world out there is unyielding and very stress intense. That is the only way they won’t become future diabetics and hypertensives.

